name: zando_art
description: Appliction de vente des oeuvres d&#x27;art.
author: Ardin Biganiro <ardinbig@gmail/com>
homepage: https://github.com/ardinbig/zando_art

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  mvc_pattern: ^3.2.1
  fluttertoast: 2.2.11
  http: ^0.12.0+1
  path: ^1.6.2
  # image_picker: ^0.4.10
  # path_provider: 0.4.1
  intl: ^0.15.7
  scoped_model: ^0.3.0
  image: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/user.jpeg
    - assets/images/logo.png


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
